### ISSUE TITLE
Problem Error

### ISSUE THREAD

**Issue by ROJOOFICIAL** [shubhayu-64/Twitter-Bot#10]
The bot does not start session I think it is because twitter changed the login link.

**Comment by DennyGerman** [comment]
@ROJOOFICIAL I have the same problem

**Comment by 600849155** [comment]
@ROJOOFICIAL I have the same problem

**Comment by shubhayu-64** [comment]
Hey @ROJOOFICIAL @DennyGerman @600849155 ,

Can you please be more precise on your issue? Include some screenshots and explanations so that I can try to resolve it. 

Cheers,
Shubhayu Majumdar

**Comment by 600849155** [comment]
> Hey @ROJOOFICIAL @DennyGerman @600849155 ,
> 
> Can you please be more precise on your issue? Include some screenshots and explanations so that I can try to resolve it.
> 
> Cheers, Shubhayu Majumdar

hey @shubhayu-64 ,under code not work ,but i has been resoleved it.Thank your replay!

        try:
            email = bot.find_element_by_name('session[username_or_email]')
            password = bot.find_element_by_name('session[password]')
        except common.exceptions.NoSuchElementException:
            time.sleep(5)
            email = bot.find_element_by_name('session[username_or_email]')
            password = bot.find_element_by_name('session[password]')

        email.clear()
        password.clear()
        email.send_keys(self.email)
        password.send_keys(self.password)
        password.send_keys(keys.Keys.RETURN)
        time.sleep(10)
        self.is_logged_in = True`
