### ISSUE TITLE
Not able to log in (selenium version)

### ISSUE THREAD

**Issue by leana8959** [shubhayu-64/Twitter-Bot#33]
Hello,

When I run the program, I can't log in.

Firstly, I think there's a problem with newer selenium versions, as they've deprecated the function `find_element_by_name` with `find_element(By.NAME, "name")`. What's the recommended version of selenium?

Secondly, I replaced some occurrences in the `login` method in `Twitter_bot` class and ran the script with the latest version of selenium(4.7.2), the script still couldn't find the field to enter login. Furthermore, the login page has changed: instead of entering both username and password in the same page, we need to first enter the username, click next, and then enter the password, and then click log in.

Thanks !

**Comment by shubhayu-64** [comment]
Hi @leana8959 I think there has been few UI changes to Twitter. If you want to make a PR to this issue, I can assign it to you.
